### ISSUE TITLE
Invalid Manual Verification Email Address

### ISSUE THREAD

**Issue by thekdub** [CraftingStore/craftingstore-docs#2]
The email address `inbound@verify.sg.craftingstore.net` found on https://github.com/CraftingStore/craftingstore-docs/blob/master/docs/general/i-did-not-get-the-confirmation-mail.md is invalid; mail cannot be delivered.

The following error is contained within the bounceback message:
```
<inbound@verify.sg.craftingstore.net>: host
    mailuser.nyi.internal[/var/run/lmtpforward/outgoing] said: 550 5.1.1
    <inbound@verify.sg.craftingstore.net>: Recipient address rejected: User
    unknown in virtual mailbox table via compute5 (in reply to end of DATA
    command)
```

```
Reporting-MTA: dns; mailuser.nyi.internal
X-Postfix-Queue-ID: 429AA21E006E
X-Postfix-Sender: rfc822; *******@*****.com
Arrival-Date: Thu, 30 Dec 2021 16:59:05 -0500 (EST)

Final-Recipient: rfc822; inbound@verify.sg.craftingstore.net
Original-Recipient: rfc822;inbound@verify.sg.craftingstore.net
Action: failed
Status: 5.1.1
Remote-MTA: dns; mailuser.nyi.internal
Diagnostic-Code: smtp; 550 5.1.1 <inbound@verify.sg.craftingstore.net>:
    Recipient address rejected: User unknown in virtual mailbox table via
    compute5
```

**Comment by Tim-NL** [comment]
Hi,

What email provider are you using? I just checked and that inbound email works just fine. It should be handled by Sendgrid, but looking at what you provided, Fastmail responded instead. But Fastmail is not used for the "verify.sg.craftingstore.net" domain.

```
;; ANSWER SECTION:
verify.sg.craftingstore.net. 300 IN	MX	10 mx.sendgrid.net.
```
--
We are using Fastmail for our domain itself (craftingstore.net). But not for our support/inbound verify/notifications mails, this will cause issues in reaching our support tickets, and more if everything is routed internally. I just set the "craftingstore.net" domain to always route externally at Fastmail. I suspect you are also using Fastmail yourself. If you do; Could you check if it works now? If not, then I'll have to create a support ticket at Fastmail. 

-Tim

**Comment by thekdub** [comment]
I'm also using fastmail for my email provider.

Just sent another email; seems to have gone through this time.

**Comment by Tim-NL** [comment]
That explains the issue because we use Fastmail for our root domain (craftingstore.net) - For the normal business-to-business emails. But not for the emails from support/notifications/the verify service. It seems like when you try to email Fastmail sees; Oh we have that domain at our service, and it tries to send it internally. But that mailbox does not exist there.

Does it work now? I updated the craftingstore.net domain to always route externally at Fastmail, but I'm not 100% sure if that also affects other Fastmail accounts. Thanks in advance! 

-- EDIT --
Thanks for the confirmation! :)

-Tim
